BOOTSTRAP_TOKEN: c4468173de5d0b4dbbea3def2e2b88fd
SERVICE_CIDR: 10.254.0.0/16
CLUSTER_KUBERNETES_SVC_IP: 10.254.0.1
CLUSTER_DNS_SVC_IP: 10.254.0.2
CLUSTER_DNS_DOMAIN: cluster.local
NODE_PORT_RANGE: 30000-50000
CLUSTER_CIDR: 172.30.0.0/16
ETCD_DATA_DIR: /etc/kubernetes/data/etcd
K8S_DIR: /etc/kubernetes/data
ENCRYPTION_KEY: 'Bt8Sb7fsMZLo1fqgkrOYJ2ns30tIOqeP/2jgs27kAsw='
KUBE_APISERVER: https://10.10.3.180:6443
ETCD_URL: "etcd01=https://10.10.3.180:2380,etcd02=https://10.10.3.181:2380,etcd03=https://10.10.3.182:2380"
ETCD_ENDPOINTS: "https://10.10.3.180:2379,https://10.10.3.181:2379,https://10.10.3.182:2379"
IFACE: ens160
DOCKER_DIR: /etc/kubernetes/data/docker

