---
- name: 设置集群参数
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/pki/ca.pem  --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=/etc/kubernetes/manifests/kubectl.kubeconfig
- name: 设置客户端认证参数
  shell: |
    kubectl config set-credentials admin --client-certificate=/etc/kubernetes/pki/admin.pem --client-key=/etc/kubernetes/pki/admin-key.pem --embed-certs=true --kubeconfig=/etc/kubernetes/manifests/kubectl.kubeconfig

- name: 设置上下文参数
  shell: |
    kubectl config set-context kubernetes --cluster=kubernetes --user=admin --kubeconfig=/etc/kubernetes/manifests/kubectl.kubeconfig

- name: 设置默认上下文
  shell: |
    kubectl config use-context kubernetes --kubeconfig=/etc/kubernetes/manifests/kubectl.kubeconfig

