---
- name: 创建docker目录
  file:
    path: "/etc/docker"
    state: directory

- name: 分配配置文件
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "/root/kubernetes-ansible/roles/docker/templates/docker.service.j2", dest: "/usr/lib/systemd/system/docker.service" }
    - { src: "/root/kubernetes-ansible/roles/docker/templates/daemon.json.j2", dest: "/etc/docker/daemon.json" }

- name: 创建数据目录
  file:
    path: "{{ K8S_DIR }}/docker"
    state: directory
